### ISSUE TITLE
프로젝트 개요 

### ISSUE THREAD

**Issue by YeThor** [YeThor/What-is-your-otter#1]
## 목적 
[토이프로젝트] 나만의 수달을 만나보자

## 기획 & 디자인 
김민재 
정연환
전형배
김나윤
임주연

## 개발
김예솔

**Comment by YeThor** [comment]
아아 @Chocoslayer 군 이 덧글이 보이나요

**Comment by Chocoslayer** [comment]
@YeThor 네 보입니다. 회사라 눈치껏 인증하고 들어옴

**Comment by YeThor** [comment]
@Chocoslayer 회사구나 ㅇㅋㅇㅋ 여기에다가 하고싶은말 적거나 새로 이슈글 파서 그때그때 생각날때마다 컨텐츠 올리면 댈듯 

나는 나대로 내가 할 수 있는것들을 하고 있겠음 ㅇㅇ

**Comment by YeThor** [comment]
여기에선 별다른 텍스트편집기는 지원하지않고, 마크다운이라는 문법을 이용하는데 혹시 궁금하면 https://gist.github.com/ihoneymon/652be052a0727ad59601 참고용 

예를 들어 `# 제목1` 이라고 치면 아래처럼 나오게 됨 (preview에서 바뀐모습 확인가능)
# 제목1

**Comment by Chocoslayer** [comment]
@YeThor Okay! I'll scheme through those guidelines and come back with some ideas.

**Comment by Chocoslayer** [comment]
@YeThor Okay! I'll skim through those guidelines and come back with some ideas.

**Comment by ny0011** [comment]
요번주부터 procreate 그림 수업 듣는데 참여 가능한 부분?😉

**Comment by brothership** [comment]
이 곳인가.. 두더지의 꿈을 이룰 곳이..

**Comment by Chocoslayer** [comment]
# 나만의 수달을 만나보자 기획안
## 프로젝트 개요
개인적 성향에 대한 복수의 문답을 통해 답변자가 본인과 어울리는 수달을 만날 수 있는 프로젝트

## 목적
1. 결과로 출력 되는 수달이 답변자의 답변을 잘 반영하고, 답변자가 문답을 진행하거나 결과를 확인하는 과정에서 **즐거움을 느낄 수 있도록** 구성하는 것
2. 프로젝트를 진행하면서 주최자 **예솔이**를 비롯, 참여자 모두가 **즐거움을 느끼는 것**

## 구성
1. 질문
1안: [5-6]개의 MECE*한 Yes or No 질문을 통해 성향을 파악하고, 답변에 따라 [32-64]개의 결과(수달)을 출력함 (*MECE: Mutually Exclusive and Collectively Exhaustive, 중복 없이 전체를 빠짐 없이 분류하는 것)
2안: 생년월일, 성별, 이름과 간단한 질문을 넣되, 랜덤으로 결과를 출력함

- 결과가 다양하게 출력 될수록 다른 답변자의 결과와 비교 등을 통해 재미를 느낄 수 있을 것으로 판단하여 30마리 이상의 수달이 적절할 것으로 예상함
- 문답을 통해 답변자의 성향을 잘 반영한 수달이 나올수록 재미를 느낄 것이라고 판단하여 1안을 우선적으로 고려하고 있으나, 질문의 구성 자체가 어렵거나 기발한 수달 아이디어를 반영하지 못하는 경우 2안이 나을 것으로 예상하여 추가함

2. 답변
답변자의 답변을 반영하여 손으로 그린 수달 그림, 수달 이름(예: 두턱수달), 설명 등을 답변자에게 보여줌
- 수달 그림의 품질에 대한 논의 필요
- 수달 이름은 브레인스토밍 형식으로 일정 부분 공모를 통해 수집하는 것이 효율적일 것으로 판단됨
- 설명은 [4-5]개의 유머러스한 문장으로 구성함

## Open Discussion
현재 질문 구성 방법으로 두 가지를 고려하고 있는데, 여러분의 의견을 듣고 싶음.
1. 질문을 먼저 생각한 뒤 답변의 경우마다 해당하는 수달을 묘사하는 방식 (질문 구성 1안과 연계)
- 답변에 따라 적절한 수달을 묘사하면 되어, 아이디어 구상과 관련한 작업이 쉬울 수 있음
- 기발한 아이디어를 반영하기 어려움

2. 자유롭게 수달을 구상한 뒤, 일정 수(약 30마리)의 샘플이 확보되면 적당한 질문을 구상하는 방식 (질문 구성 2안과 연계)
- 기발한 아이디어를 반영할 수 있음
- 질문과 크게 연관이 없는 결과가 출력되기 때문에, 몰입도가 낮을 수 있음
- 이 경우, 수달 그림의 품질이 프로젝트의 핵심이 될 가능성이 있음

3. 기타 방식
자유롭게 제안해주세요

회사에서 몰래 대충 작성해 봤습니다. **Feel free to comment!**

**Comment by ny0011** [comment]
자유롭게 수달을 구상해본 후 기발한 아이디어가 나오지 않는다 싶으면 
질문에 맞는 수달을 만드는게 편해 보입니다~
하지만 쵸코슬레이어님과 부라더쉽님이 계시니...^ㅅ^

**Comment by YeThor** [comment]
이야 많이들왔네

**Comment by nateray42** [comment]
에-롭

**Comment by YeThor** [comment]
구체적인 참여 가이드는 https://github.com/YeThor/What-is-your-otter/issues/5 로,
민재가 남긴 수달 기획은 https://github.com/YeThor/What-is-your-otter/issues/2 로 진행하겠으며
해당 이슈는 닫겠습니다.

**Comment by YeThor** [comment]
@nateray42 @JuyeonLim 이메일로 초대링크 안갔으면 알려주세여
