### ISSUE TITLE
수달 이름, 설명, 이미지

### ISSUE THREAD

**Issue by Chocoslayer** [YeThor/what-is-your-otter#11]
### 수달프로젝트 타임라인 공지

본 프로젝트 초기에 최소 30마리의 수달을 확보하자는 협의가 있었습니다. 현재 6명의 참여 인원(예솔, 나윤, 민재, 형배, 주연, 연환)을 고려하여 **5월 5일 어린이날까지 각자 5~6 마리**의 수달을 데려오시면 적절할 것 같습니다. 적정한 수의 수달이 모이면 질문 이슈를 새로 작성하여 논의를 거친 후 질문 작성 가이드라인을 공지하겠습니다.
제가 제시하는 타임라인은 아래와 같습니다.

04/13 - **05/18**: 수달 그림 최소 30마리 확보
05/12: 수달 프로젝트 질문 이슈 생성 및 가이드라인(논의 요) 공지
05/12 - **05/26**: 수달 프로젝트 질문 작성 및 선정 완료

### 수달 그림 가이드라인 공지

저는 여러분의 다양한 그림 스타일을 반영하고 싶습니다. 따라서 최소한의 가이드라인만 설정합니다.
원칙적으로 하기 가이드라인을 준수하시되, 그 외의 스타일은 개인의 취향껏 자유로이 표현해 주세요.
필요할 경우 가이드라인에서 벗어나셔도 좋습니다(어휘를 규격에서 가이드라인으로 변경한 이유ㅎㅎ).
이해를 돕기 위한 예시 이미지를 본문 하단에 첨부합니다.

수달의 **이름**과(예: 두턱수달) **간단한 설명**(게으르고 먹는 것을 좋아하는 평범한 수달이 누워서 스마트폰하는 모습 등), **수달 그림 파일**을 본 이슈 내에 게시해 주세요. 결과물로는 이름과 그림이 출력될 예정이며, 이름과 그림이 의도한 바를 잘 반영했는지 설명을 읽고 상호 피드백하시면 됩니다.

### 그림 가이드라인
**1. 머리는 가로로 긴 타원형**
- 머리를 여러 형태로 그려본 결과, 원형에 가까울 수록 다른 동물(곰 등)로 오인될 수 있습니다.

**2. 귀는 조그마한 원형**
- 다른 동물로 오인될 수 있습니다.

**3. 코를 기준으로 비스듬히 올라오는 무늬**
- 수달 캐릭터화의 핵심입니다.

### 예시 이미지

![20190413_175523 1](https://user-images.githubusercontent.com/47937050/56077381-7105ae80-5e16-11e9-94fa-a9e78614a02e.jpg)
![20190413_175528 1](https://user-images.githubusercontent.com/47937050/56077389-9d212f80-5e16-11e9-8076-99cce7f25fe7.jpg)

**Comment by brothership** [comment]
질문! 혹시 작업중인 수달이 곂치는 경우가 발생할 수 있을 것 같은데 일단 완성품을 받고나서 추후에 수정하는 식으로 대처하는 건가요?

**Comment by Chocoslayer** [comment]
@brothership
우선 본인의 아이디어를 그림으로 그려오는 걸 원칙으로 합니다. 다만 다른 사람의 아이디어도 그려보고 싶다면 해당 아이디어 제안자의 동의 하에 그림을 게시하고 최종 선택을 할 예정입니다. 최종 선택의 방법으로는 제 판단, 제안자의 결정, 다수결 등이 있으나 특이사항이 없다면 제안자가 결정하는 방식을 채택할 예정입니다.

**Comment by brothership** [comment]
@Chocoslayer 제출한 아이디어가 1개 뿐이라 물어봤습니다 ㅎㅎ 일단 현조님의 아이디어 사용을 고려해보도록 하죠

**Comment by ny0011** [comment]
@Chocoslayer  [스파수달](https://user-images.githubusercontent.com/22537805/57028016-ea0b5f80-6c78-11e9-87a1-c1236c61c3ac.png)
링크 누르면 보일겁니다

모바일에서 그림파일 쉽게 올리는 법 아시는분...

**Comment by YeThor** [comment]
? 저는 개발만 하기에도 벅찹니다 기획 디자인에선 빼주시죠  👍

**Comment by ny0011** [comment]
> @brothership
> 우선 **본인의 아이디어를 그림으로** 그려오는 걸 원칙으로 합니다. 다만 다른 사람의 아이디어도 그려보고 싶다면 해당 아이디어 **제안자의 동의 하에** 그림을 게시하시면 되고, 그 중 최종 선택을 할 예정입니다. 최종 선택의 방법으로는 제 판단, 제안자의 결정, 다수결 등이 있으나 특이사항이 없다면 제안자가 결정하는 방식을 채택할 예정입니다.
> 
> 2019/04/14 추가
> 수달 프로젝트의 수달 아이디어 생산팀에 **17기 양현조님**이 참여하기로 결정되었으니, 아이디어가 잘 떠오르지 않는다면 현조님의 아이디어를 그려보는 방법을 추천합니다.

본인이 만들 수달을 미리 여기에 공유해주면 겹치지 않을거 같아용

**Comment by ny0011** [comment]
> ? 저는 개발만 하기에도 벅찹니닷 기획 디자인에선 빼주시죠 👍

님 어디가요
귀찮수달 만들어죠요

**Comment by ny0011** [comment]
> @Chocoslayer [스파수달](https://user-images.githubusercontent.com/22537805/57028016-ea0b5f80-6c78-11e9-87a1-c1236c61c3ac.png)
> 링크 누르면 보일겁니다
> 

+ 인별수달, 미각수달 추가 예정

**Comment by YeThor** [comment]
> 수달 프로젝트의 수달 아이디어 생산팀에 17기 양현조님이 참여하기로 결정되었으니, 아이디어가 잘 떠오르지 않는다면 현조님의 아이디어를 그려보는 방법을 추천합니다. 

아직 현조나 민재한테 전해받은 현조 github 아이디가 없음. 이 저장소에 접근권한이 있을지 모르겠는데, 암튼 그렇다구여 'ㅅ'

**Comment by Chocoslayer** [comment]
> 아직 현조나 민재한테 전해받은 현조 github 아이디가 없음. 이 저장소에 접근권한이 있을지 모르겠는데, 암튼 그렇다구여 'ㅅ'

나도 현조에게 따로 받은 건 없어서 확인차 연락 한 번 해보겠읍니다. 디자인&기획 제외 부분도 확인했음~!

**Comment by Chocoslayer** [comment]
**두턱수달**
- 게으르고 뒹굴거리는 것을 좋아하는 평범한 수달이 누워서 스마트폰하는 모습
![1556966336542 1](https://user-images.githubusercontent.com/47937050/57178000-34712400-6ea5-11e9-9114-b0f6f53fa6e8.jpg)

**Comment by Chocoslayer** [comment]
**근성수달**
- 힘겨운 상황에서 끈질기게 버티고 있는 수달이 의지를 불태우는 모습
![1556967562147 1](https://user-images.githubusercontent.com/47937050/57178288-da725d80-6ea8-11e9-8101-f60aea930f9f.jpg)

**Comment by Chocoslayer** [comment]
**운동수달**
- 열심히 운동하는 수달의 모습
![1556969692379 1](https://user-images.githubusercontent.com/47937050/57178523-810c2d80-6eac-11e9-95d0-27f275006d0a.jpg)

**Comment by Chocoslayer** [comment]
**성실수달**
- 성실하게 일/공부하는 수달의 모습
![1556971000220 1](https://user-images.githubusercontent.com/47937050/57178682-4a83e200-6eaf-11e9-91b8-455a84f79a70.jpg)

**Comment by Chocoslayer** [comment]
**만취수달**
- 친구들과 즐겁게 건배하는 수달의 모습
![1556971908407 1](https://user-images.githubusercontent.com/47937050/57178817-65efec80-6eb1-11e9-9d7f-7c6a4a5a848b.jpg)

**Comment by ny0011** [comment]
![인별수달](https://user-images.githubusercontent.com/22537805/57181722-33a2b700-6ed2-11e9-8da6-639bc03c0466.png)
**인별수달**
SNS에 사진을 올리고 좋아요 받는 걸 좋아한다

**Comment by ny0011** [comment]
![미각수달](https://user-images.githubusercontent.com/22537805/57181688-db6bb500-6ed1-11e9-9d7b-d1db25437725.png)

**미각수달**
맛있는 음식을 먹는 것을 좋아한다

**Comment by brothership** [comment]
안경수달인데 안경을 벗고 누웠어요
![IMG_0349](https://user-images.githubusercontent.com/47941321/57191269-81650100-6f5e-11e9-9c0d-75d2234b1a5d.jpeg)

**Comment by brothership** [comment]
@Chocoslayer 일단 내가 냈던 아이디어는 그렸는데 또 무엇을 그리면 좋을까요?

+ 채색은... 추후 작업하겠습니다

**Comment by ny0011** [comment]
![지름수달](https://user-images.githubusercontent.com/22537805/57192246-49af8680-6f69-11e9-82df-7d16fee681c6.png)
**지름수달**
일단 질러버려!

**Comment by ny0011** [comment]
![둠칫수달](https://user-images.githubusercontent.com/22537805/57192268-7cf21580-6f69-11e9-8020-bc5e1e0a6409.png)

**둠칫수달**
둠칫둠칫 두둠칫

**Comment by ny0011** [comment]
@brothership 게임수달이랑 덕후수달 그려줘여

**Comment by JuyeonLim** [comment]
허세수달
- 오픈카를 타고 다니는 수달은 어딘가 촌스럽다.
- 땡땡이 스카프와 하얀 썬글라스가 그의 차밍포인트인줄 안다.
- 다른 여자 수달을 꼬시고 싶어만 하고,,,별 소득은 없다.

<img width="1112" alt="IMG_0054" src="https://user-images.githubusercontent.com/16059210/57192534-8335c100-6f6c-11e9-9e9a-87d3d15ccb8d.png">

**Comment by JuyeonLim** [comment]
궁예수달
- “지금 누가 조개소리를 내었는가?” 로 모든 걸 말해주는 수달
- 관심법을 쓸 줄 안다.

<img width="1112" alt="IMG_0055" src="https://user-images.githubusercontent.com/16059210/57192553-b7a97d00-6f6c-11e9-8d99-2a55570ee127.png">

**Comment by JuyeonLim** [comment]
킬러수달
- 해맑은 표정으로 명중률 99퍼를 자랑하는 수달
- 레이저 조준경과 후레쉬가 달린 총을 늘 소지하고 있다.
- 연발로 악랄하게 킬링 썸원

<img width="632" alt="IMG_0053" src="https://user-images.githubusercontent.com/16059210/57192580-0ce58e80-6f6d-11e9-98d2-48da88ecf4e3.png">

**Comment by JuyeonLim** [comment]
수웩수달
- 쇼미더쉘 에서 우승을 차지한 천재래퍼
- 그의 패션 하나하나가 모두의 이목을 끈다.

<img width="687" alt="IMG_0052" src="https://user-images.githubusercontent.com/16059210/57192627-84b3b900-6f6d-11e9-8545-08f7cf711c64.png">

**Comment by JuyeonLim** [comment]
윤민수달
- 윤민수를 꿈꾸는 윤민수달
- 윤민수의 창법과 표정 하나하나 일치하는 싱크로율은 동물계를 놀라게 했다.
- 조만간 3집이 발매될 예정

**Comment by quss135** [comment]
![9843457F-1F76-4C5A-9B1E-FB2C25A58131](https://user-images.githubusercontent.com/49609010/57195317-ff8bcc80-6f8b-11e9-823a-2284d4463eb7.jpeg)
• 볼 거 많수달 

- 남들 다 보길래 나도 따라서 정액권을 끊어봄 
- 막상 정액권 끊어놓으면 보지도 않음
- 근데 추천 목록은 산더미처럼 저장해놓음

**Comment by quss135** [comment]
![928F072B-BC91-4BEA-B7FE-1921664D8C69](https://user-images.githubusercontent.com/49609010/57195357-71fcac80-6f8c-11e9-95e0-dafe5a505a6f.jpeg)
• 휴가계획 짰수달 

- 휴가계획 짜는 지금만큼은 마음만은 바캉스
- 휴가계획 짤 때가 제일 즐거움

**Comment by quss135** [comment]
![B0122178-DF9D-4607-BA1A-05BB6BB0CF9C](https://user-images.githubusercontent.com/49609010/57195381-ac664980-6f8c-11e9-9488-06234eda3113.jpeg)
• 힐링 에세이 읽수달 

- 남들이, 그리고 내가 나를 힘들게 하는 날엔 나만의 시간을 갖자 
- 힐링되는 에세이 한 권과 따뜻한 라떼의 조합
- 위로가 필요한 당신에게 토닥토닥

**Comment by quss135** [comment]
충청도와 가까운 평택 사람이라 그런지 ~슈 라는 말투에 아이디어를 얻어 네이밍 해보았습니다. 다른 분들은 어떻게 읽으실지 모르겠네요ㅠㅠ 금손들이 너무나 많아!

**Comment by brothership** [comment]
![IMG_0351](https://user-images.githubusercontent.com/47941321/57383939-a40b4a00-71ea-11e9-89f6-db8db42b98c8.jpeg)
세싱에나 다들 금손이야... 일단 채색된 안경수달입니다

**Comment by Chocoslayer** [comment]
Timeline Updated as below:

04/13 - **05/18**: 수달 그림 최소 30마리 확보
05/12: 수달 프로젝트 질문 이슈 생성 및 가이드라인(논의 요) 공지
05/12 - **05/26**: 수달 프로젝트 질문 작성 및 선정 완료

**Comment by chj1001** [comment]
![KakaoTalk_20190512_150048115](https://user-images.githubusercontent.com/42489301/57583289-fa1c0e00-74c6-11e9-907e-54a804fc4f3c.jpg)
**셰프수달**
조개요리의 권위자 a.k.a 수달계의 고든램지
맛없는 요리는 납득하지 못하는 성격

**Comment by nateray42** [comment]
![해달](https://user-images.githubusercontent.com/47944877/57584037-e0ec7f00-7511-11e9-95c3-b27cb9969fd8.jpg)

해달

Praise the sun

- 수달들의 숭배 대상.

- 수달들은 태양을 보며 큰 수달신이 태양빛을 내려 준다고 생각한다.

**Comment by nateray42** [comment]
![우비수달](https://user-images.githubusercontent.com/47944877/57584080-640dd500-7512-11e9-86e5-e4567ac49f41.jpg)

우비수달

- 실은 수달 주제에 헤엄을 못 친다.

- 하지만 물과 비오는 날은 굉장히 좋아함.

- 다른 친구 수달들이 물에서 놀 동안, 혼자 우비를 쓰고 다닌다. 하지만 행복해.

**Comment by brothership** [comment]
<img width="800" alt="IMG_0354" src="https://user-images.githubusercontent.com/47941321/57979087-97d98500-7a53-11e9-8cb3-aacd923860a0.png">


재테크 수달

 + 디트코인과 주식등 투자를 즐기는 수달

 + 수익성은 보장 받지 못함 주의

**Comment by nateray42** [comment]
아이디어 :

수파르달

투구를 쓰고 있는 군인수달. 모두를 지키기 위해서 노력을 거듭하지만 동료에게서 지나치게 딱딱하다는 평가를 받는다.

**Comment by ny0011** [comment]
![99640F75-AE26-4204-BA7E-3957AA0F6B7D](https://user-images.githubusercontent.com/22537805/58442298-e4445500-8124-11e9-8a0f-6c0acd4d6bcd.png)
![B37C1A49-8451-41AE-8DF2-537FF4B6D90A](https://user-images.githubusercontent.com/22537805/58442299-e4dceb80-8124-11e9-8740-87fd726b71bc.png)
![8DF0FC6A-E2C5-4E25-84AF-29F363FB780E](https://user-images.githubusercontent.com/22537805/58442300-e4dceb80-8124-11e9-8378-c51cf4acf9d6.png)

@Chocoslayer 색칠 추가 완료요

**Comment by YeThor** [comment]
모두들 수고하셨어요. 프로젝트 완료로 이슈 클로즈합니다 https://yethor.github.io/what-is-your-otter/index.html
