### ISSUE TITLE
수달 질문

### ISSUE THREAD

**Issue by Chocoslayer** [YeThor/what-is-your-otter#12]
### 수달 질문 모음에 관한 논의

여러분! 각자의 개성을 담은 그림들을 모아주셔서 감사합니다.
이제 **5월 26일(일)까지** 이용자가 수달을 만나기 전에 받을 질문들을 모을 예정입니다.

우선 본 프로젝트가 기술적으로 어떤 형태로 구현되어 있는지 예솔이의 설명을 들은 뒤, 질문 작성에 관한 논의를 최대 **이번 주말(2019.05.19)까지** 진행하고 가이드라인 공지 및 질문 취합을 시작하겠습니다.

**Comment by YeThor** [comment]
> 우선 본 프로젝트가 기술적으로 어떤 형태로 구현되어 있는지 예솔이의 설명을 들은 뒤,

? 이런말이 있는걸 지금봄;

**Comment by YeThor** [comment]
이건 그냥 님들이 정해주면 따라가겠음

**Comment by YeThor** [comment]
민재야 고생많았당
