### ISSUE TITLE
수달 기획 & 디자인 

### ISSUE THREAD

**Issue by YeThor** [YeThor/what-is-your-otter#2]
> 민재가 작성한 초기 기획안 그대로 긁어옴 

# 나만의 수달을 만나보자 기획안
## 프로젝트 개요
개인적 성향에 대한 복수의 문답을 통해 답변자가 본인과 어울리는 수달을 만날 수 있는 프로젝트

## 목적
1. 결과로 출력 되는 수달이 답변자의 답변을 잘 반영하고, 답변자가 문답을 진행하거나 결과를 확인하는 과정에서 **즐거움을 느낄 수 있도록** 구성하는 것
2. 프로젝트를 진행하면서 주최자 **예솔이**를 비롯, 참여자 모두가 **즐거움을 느끼는 것**

## 구성
1. 질문
   1안: [5-6]개의 MECE*한 Yes or No 질문을 통해 성향을 파악하고, 답변에 따라 [32-64]개의 결과(수달)을 출력함 (*MECE: Mutually Exclusive and Collectively Exhaustive, 중복 없이 전체를 빠짐 없이 분류하는 것)
   2안: 생년월일, 성별, 이름과 간단한 질문을 넣되, 랜덤으로 결과를 출력함

* 결과가 다양하게 출력 될수록 다른 답변자의 결과와 비교 등을 통해 재미를 느낄 수 있을 것으로 판단하여 30마리 이상의 수달이 적절할 것으로 예상함
* 문답을 통해 답변자의 성향을 잘 반영한 수달이 나올수록 재미를 느낄 것이라고 판단하여 1안을 우선적으로 고려하고 있으나, 질문의 구성 자체가 어렵거나 기발한 수달 아이디어를 반영하지 못하는 경우 2안이 나을 것으로 예상하여 추가함

1. 결과
   답변자의 답변을 반영하여 손으로 그린 수달 그림, 수달 이름(예: 두턱수달), 설명 등을 답변자에게 보여줌

* 수달 그림의 품질에 대한 논의 필요
* 수달 이름은 브레인스토밍 형식으로 일정 부분 공모를 통해 수집하는 것이 효율적일 것으로 판단됨
* 설명은 [4-5]개의 유머러스한 문장으로 구성함

## Open Discussion
현재 질문 구성 방법으로 두 가지를 고려하고 있는데, 여러분의 의견을 듣고 싶음.

1. 질문을 먼저 생각한 뒤 답변의 경우마다 해당하는 수달을 묘사하는 방식 (질문 구성 1안과 연계)

* 답변에 따라 적절한 수달을 묘사하면 되어, 아이디어 구상과 관련한 작업이 쉬울 수 있음
* 기발한 아이디어를 반영하기 어려움

1. 자유롭게 수달을 구상한 뒤, 일정 수(약 30마리)의 샘플이 확보되면 적당한 질문을 구상하는 방식 (질문 구성 2안과 연계)

* 기발한 아이디어를 반영할 수 있음
* 질문과 크게 연관이 없는 결과가 출력되기 때문에, 몰입도가 낮을 수 있음
* 이 경우, 수달 그림의 품질이 프로젝트의 핵심이 될 가능성이 있음

1. 기타 방식
   자유롭게 제안해주세요

회사에서 몰래 대충 작성해 봤습니다. **Feel free to comment!**

----------------------------------------------------------
민재가 정리해 올려준 기획안 
[수달+프로젝트_KMJ_20190804.xlsx](https://github.com/YeThor/what-is-your-otter/files/4015666/%2B._KMJ_20190804.xlsx)

**Comment by YeThor** [comment]
수달 관련해서는 여기 덧글로 계속 얘기 이어나가면 될듯함 👍

**Comment by YeThor** [comment]
> ## Open Discussion
> 현재 질문 구성 방법으로 두 가지를 고려하고 있는데, 여러분의 의견을 듣고 싶음.
>  1. 질문을 먼저 생각한 뒤 답변의 경우마다 해당하는 수달을 묘사하는 방식 (질문 구성 1안과 연계)
>  2. 자유롭게 수달을 구상한 뒤, 일정 수(약 30마리)의 샘플이 확보되면 적당한 질문을 구상하는 방식 (질문 구성 2안과 연계)

**2안을 지지함**

- 질문이야 재미용도로 뽑아낼수 있지만, 
- 특징있는 수달캐릭터 30마리를 창작하는게 쉬운일은 아닐 것
- 일단 손가는대로 생각나는대로 32마리의 수달을 창작하고 (꼭 32마리가 아니여도 된다고 생각함. 몇가지 경우끼리는 중복수달 어느정도 가져도 괜찮다고 생각.) 
- 거기에 맞춰 드립을 치면서 질문작성하면서 가다듬어가는게 좋지 않을까 싶음 

그때그때 생각날때마다 아이디어 적어두고 살 붙여가면 좋을것같음

**Comment by ny0011** [comment]
물속에서 하루종일 멍때리고 누워있는 수달 하나요

**Comment by YeThor** [comment]
피곤에 쩔어있는 수달 하나요 

- 다크서클, 조금 찌푸린 듯한 미간 , 피곤에 쩔어있는 직장인 느낌
- 피곤에 쩔어있는 수달. 스트레스. 항상 쉬고싶다 퇴사하고싶다 귀찮다가 입에 붙어있지만 이리 치이고 저리 치이느라 실제로는 스스로를 돌볼 시간이 없음. 하루 연차내고 태평양으로 떠나자

**Comment by YeThor** [comment]
귀차니즘에 쩔어있는 수달 하나요

- 서있는것도 귀찮아서 누워있는 모양새 
- 조개도 들고있기 귀찮아서 목에 걸고 다님...
- `모든게 다 귀찮아`가 입에 붙은 당신. 이제는 귀찮아 라고 말하는것마저 귀찮다

**Comment by Chocoslayer** [comment]
> ## Open Discussion
> 현재 질문 구성 방법으로 두 가지를 고려하고 있는데, 여러분의 의견을 듣고 싶음.
> 1. 질문을 먼저 생각한 뒤 답변의 경우마다 해당하는 수달을 묘사하는 방식 (질문 구성 1안과 연계)
> 2. 자유롭게 수달을 구상한 뒤, 일정 수(약 30마리)의 샘플이 확보되면 적당한 질문을 구상하는 방식 (질문 구성 2안과 연계)

저도 2안이 낫다고 생각합니다. 그럼 자유롭게 수달 샘플을 추가하는 형식으로 진행합시다. 톡방에도 아이디어 공모 받는다고 알리면 좋을 것 같습니다.

p.s. 수달 그림의 품질은 사실 반 농담으로 언급한 것이었는데, 그림 자체의 심미적 기준보다는 기본적인 규격의 통일성 관련 내용으로 생각해주시면 될 것 같습니다.
예시
> - 무늬 없는 배경 (연습장 줄 등이 없는)
> - 그림 사이즈
> - 그 외 기본적인 규격 관련

**Comment by Chocoslayer** [comment]
ㅋㅋㅋㅋㅋㅋㅋ김예솔 김나윤 생각한 수달들 봐ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ너무 본인들이 반영된 것 아닙니까..?

**Comment by Chocoslayer** [comment]
**두턱수달**
- 게으르고 먹는 것을 좋아하는 평범한 수달이 누워서 스마트폰하는 모습
- 두턱, 스마트폰, 누운 자세 묘사 필요

**Comment by Chocoslayer** [comment]
**근성수달**
- 힘겨운 상황에서 끈질기게 버티고 있는 수달이 의지를 불태우는 모습
- 불꽃눈, 근엄하게 서 있는 포즈, 등 뒤로 불꽃과 함께 작업물(서류, 펜, 드링크 등) 묘사 필요

**Comment by Chocoslayer** [comment]
**운동수달**
- 열심히 운동하는 수달의 모습
- 운동기구(덤벨, 바벨, 러닝머신 등 알기 쉬운 것), 헤어밴드, 운동하는 포즈 묘사 필요

**Comment by Chocoslayer** [comment]
**성실수달**
- 성실하게 일/공부하는 수달의 모습
- 안경, 일부 만화적 표현(땀 흘리는 등), 집중한 듯한 표정(혀를 무는 등) 묘사 필요

**Comment by Chocoslayer** [comment]
**만취수달**
- 친구들과 즐겁게 건배하는 수달의 모습
- 술잔, 홍조, 뱅뱅 도는 눈(혹은 빛나는 눈), 일어서서 건배하는 포즈 묘사 필요
- 넥타이를 머리에 두른다거나, 휘청거리는 모습은 제외

**Comment by YeThor** [comment]
**가오수달**

- 폼생폼사
- 그런데 허당임 
- 그럴싸하게 옷도 차려입고 머리도 잘 빗어올린듯한 모양새지만, 사실 단추가 하나씩 엇갈려끼워져있다
- 사실 티셔츠도 자세히보면 앞뒤 바꿔입음..
- 하지만 표정만큼은 `내가 세상에서 제일 멋있어` 자신감에 가득 차있다

**Comment by YeThor** [comment]
수달이름 4글자로 통일시키는것도 귀여울지도?
귀찮수달
피곤수달

**Comment by Chocoslayer** [comment]
> **가오수달**
> 
> * 폼생폼사
> * 그런데 허당임
> * 그럴싸하게 옷도 차려입고 머리도 잘 빗어올린듯한 모양새지만, 사실 단추가 하나씩 엇갈려끼워져있다
> * 사실 티셔츠도 자세히보면 앞뒤 바꿔입음..
> * 하지만 표정만큼은 `내가 세상에서 제일 멋있어` 자신감에 가득 차있다

@YeThor 가오수달은 허세수달로 이름을 바꿔보는 것이 어떨까 제안합니다ㅎㅎ

**Comment by YeThor** [comment]
상관없음 디테일적인 결정사항은 너에게 맡김 ㅎㅎ

**Comment by YeThor** [comment]
이스터에그로 민재수달 같은거 들어가면 어때 for honor

**Comment by YeThor** [comment]
까비

**Comment by Chocoslayer** [comment]
for honor가 for kakao로 보이는 기적.....게임을 너무 많이 했나 보다. 앗 새로운 수달 아이디어가 떠올랐다.

**폐인수달**
- 게임에 중독되어 hair나오지 못하는 수달
- 헤드셋, 얼굴에 비친 모니터의 빛, 키보드&마우스, 집중한 표정 묘사 필요

**Comment by YeThor** [comment]
` 헤드셋, 얼굴에 비친 모니터의 빛, 키보드&마우스, 집중한 표정 묘사 필요` 개발자 수달같은데..

**Comment by brothership** [comment]
## 안경수달

>*운동 신경이 떨어지는 약간 둔한 수달
>*안경은 은근 자주 잃어버려서 허우적허우적 거리는게 매력뽀인뜨
>*안경을 쓰고 있어 지적인 이미지로 보이나 사실은 허당

**Comment by ny0011** [comment]
수달이 기본형 그려보았당
수달로 보이는지 선생님들의 고견을 묻습니다
![kakaotalk_20190306_223719177](https://user-images.githubusercontent.com/22537805/53885237-90176080-4060-11e9-88af-b9a96d3a3cbd.png)
![kakaotalk_20190306_223747101](https://user-images.githubusercontent.com/22537805/53885238-90176080-4060-11e9-84f8-bf69d6443feb.png)

**Comment by YeThor** [comment]
@Chocoslayer 기획자님 위 그림 확인부탁드림니다~

**Comment by JuyeonLim** [comment]
나윤언니 그림 보고 얼굴에 수달 느낌의 채색을 더해보았습니다~!
화살표 표시가 그나마 제일 나은 수달!


![img_9043](https://user-images.githubusercontent.com/16059210/53966720-11412700-4137-11e9-8807-69ecf1be2c64.jpg)

**Comment by YeThor** [comment]
아..치유된다..

**Comment by ny0011** [comment]
후앙 기여워....!!!!

**Comment by Chocoslayer** [comment]
졸귀

**Comment by JuyeonLim** [comment]
![7309F296-8282-49AC-825F-50B1832E2A23](https://user-images.githubusercontent.com/16059210/54817273-dd8b0300-4cd9-11e9-8053-ff2e9b8ede6c.png)
![9F53F20B-C380-49C0-9F1E-3F913E62E8F0](https://user-images.githubusercontent.com/16059210/54817274-de239980-4cd9-11e9-81c3-9139cd2bcf29.png)
![9B7764DF-40B0-4A35-A3EF-A7396C7F3FAA](https://user-images.githubusercontent.com/16059210/54817275-de239980-4cd9-11e9-8040-fa3ac34c7e5a.png)

게임광고 영상에 수달(?)해달(?)이 나오길래 참고하려고 캡쳐했숩니다!

**Comment by nateray42** [comment]
https://ciy-totem.com/

하나하나 그리는 건 자원이 많이 들어갈 수 있기 때문에 위 링크의 도트나 어플 중에 나의 최애캐 만들기 처럼 부품을 만든 다음 경우의 수에 따라 조립하는 건 어떨까요?

물론 저렇게 하면 기획에서 나왔던 다양성이나 개성은 좀 떨어질 가능성이 큽니다.

**Comment by YeThor** [comment]
@chocoslayer 메인이 되는 누군가가 기획디자인쪽은 확실히 드라이빙을 했으면 좋겠습니다. 
상황이 여의치 않다면 알려주세요. 다른사람이 드라이빙해도 되구요. 일단은 4월말까지 메인컨텐츠 1차초안 나왔으면 합니다.(단순히 그림, 질문지 텍스트 개별 파일이 아닌, 하나로 엮인 정리된 컨텐츠요)


이대로 아이디어만 오고가다가 프로젝트 유야무야되는건 개발에 시간쏟은 제 입장에선 달갑지 않은 일일인데, 뭔가 얘기만 나오고 정리가 안되는 것 같아서 노파심에 코멘트 남깁니다.

**Comment by YeThor** [comment]
4월말~5월 중순까지 진행되는게 없으면 이 프로젝트는 클로즈할게욥

**Comment by Chocoslayer** [comment]
@YeThor  확인했습니다.

**Comment by Chocoslayer** [comment]
### 수달 작화 가이드라인 공지

저는 여러분의 다양한 작화 스타일을 반영하고 싶습니다. 따라서 최소한의 가이드라인만 설정합니다.
원칙적으로 하기 가이드라인을 준수하시되, 그 외의 스타일은 개인의 취향껏 자유로이 표현해 주세요.
필요할 경우 가이드라인에서 벗어나셔도 좋습니다(어휘를 규격에서 가이드라인으로 변경한 이유ㅎㅎ).
이해를 돕기 위한 예시 이미지를 본문 하단에 첨부합니다.

수달의 **이름**과(예: 두턱수달) **간단한 설명**(게으르고 먹는 것을 좋아하는 평범한 수달이 누워서 스마트폰하는 모습 등), 결과물로 출력될 **이미지 파일**을 본 이슈 내에 게시해 주세요.

**질의는 이곳 수달 기획 & 디자인 이슈에서 진행합니다. **


### 작화 가이드라인
**1. 머리는 가로로 긴 타원형**
- 머리를 여러 형태로 그려본 결과, 원형에 가까울 수록 다른 동물(곰 등)로 오인될 수 있습니다.

**2. 귀는 조그마한 원형**
- 다른 동물로 오인될 수 있습니다.

**3. 코를 기준으로 비스듬히 올라오는 무늬**
- 수달 캐릭터화의 핵심입니다.


### 예시 이미지

![20190413_175523 1](https://user-images.githubusercontent.com/47937050/56077381-7105ae80-5e16-11e9-94fa-a9e78614a02e.jpg)
![20190413_175528 1](https://user-images.githubusercontent.com/47937050/56077389-9d212f80-5e16-11e9-8076-99cce7f25fe7.jpg)

**Comment by YeThor** [comment]
여러분 드디어 완성되었습니다~ https://yethor.github.io/what-is-your-otter/index.html

프로젝트 완료되어 이만 모든 이슈를 정리하고 닫겠습니다 ㅎ_ㅎ

**Comment by ny0011** [comment]
예솔아 고생 많았어!👍
