### ISSUE TITLE
프로젝트 임시 중단 건의 

### ISSUE THREAD

**Issue by YeThor** [YeThor/what-is-your-otter#20]
프로젝트가 오래 질질 끌리는 것 같아 해당 프로젝트를 임시 중단 상태로 바꾸고자 합니다. 
여러분이 그려주신 그림은 다른 프로젝트에서 활용할 수 있는지 고민해볼게욥.

별다른 의견이 없다면 한달 후에 해당 저장소는 닫도록 하겠습니다.

**Comment by Chocoslayer** [comment]
안 그래도 오늘 하반기 넘어가기 전에 의사결정수 마무리지어서 보내드릴 예정이었는데 내가 너무 일언반구 없었다ㅋㅋㅋㅋㅋㅋ일단 보내드리고 카톡 드리겠습니다.
