### ISSUE TITLE
두더지 기획 & 디자인 

### ISSUE THREAD

**Issue by YeThor** [YeThor/what-is-your-otter#3]

**Comment by YeThor** [comment]
두더지의 꿈을 펼치고 싶은자 이리로 오라

**Comment by YeThor** [comment]
삼성 두더지
엘지 두더지
애플 두더지

**Comment by brothership** [comment]
@YeThor
OMG

**Comment by brothership** [comment]
프로젝트 개요
------------------
------------------

디지털 반려 두더지
반려동물 양육이나 식물 기르기를 해보고 싶으나 금전,시간적으로 부담이되는 현대인들을 위해 대안을 제시한다

목적
---------------
1. 항상 같은 루틴에 갇혀 삶에 무료해진 현대인들에게 활력소가 되어줌
2. 두더집사들이 모여서 서로의 즐거웠던 경험을 공유해 새로운 커뮤니티를 구성할 수 있게 도와준다

구성
--------------------
* 유저가 전혀 생각하지 못한 순간에 화면에 등장하여 유저를 당황하게 하는 두더지
* 등장한 두더지와 interaction할 수 있는 수단(떼리기, 먹이주기, 모자 씌워주기, 쓰담쓰담 등)
* Funny moment가 발생하면 이를 자동으로 기록해 줄 수 있는 auto cam

오픈 디스커션
-----------------
1. 두더지의 생김새
 > Real한 생김새? 상업적인 귀여움? 약간은 하찮음?
 >> * Real한 생김새는 따로 장점을 못찾겠음.. 오히려 기분 나쁠 듯..
 >> * 상업적인 귀여움은 폰게임 일러에 나올법한 귀여움인데 너무 뻔하지 않을까?
 >> * 약간은 하찮음은 유저 자신이라도 그릴 수 있는 하찮은 형상에서 마음의 평화가 오지 않을까?(사실 만들 수 있는 퀄리티가 여기가 한계..

2. 구현 디바이스
 > PC? 안드로이드? iOS?
 >> 사실 이상적인건 모든 디바이스 연동이나 현실적이지 않은 것 같음...

**Comment by brothership** [comment]
좋은 아이디어 있으면 지나가는 말로 던져주시면 감사하겠습니다.

아무도 안달아주면... 어,,쩔,,,,수,,없,,ㅈ;,,,

**Comment by brothership** [comment]
<img width="1194" alt="img_0159" src="https://user-images.githubusercontent.com/47941321/53563434-5691b180-3b97-11e9-83a6-0a4498bfea7b.png">

하찮은 두더지 초안

**Comment by YeThor** [comment]
헐 귀여워 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by YeThor** [comment]
아니 근데 기획안에 있는 스펙보니까 이건 완전 다른 프로젝트인데.............?

**Comment by brothership** [comment]
생각했던건 백그라운드에 깔린 형태라 전혀 다른 느낌이긴 하죠...

**Comment by YeThor** [comment]
>  유저가 전혀 생각하지 못한 순간에 화면에 등장하여 유저를 당황하게 하는 두더지
이건 웹 개발이 아니라 프로그램 개발에 더 가까운 느낌이네요... 
어쨌든 컴퓨터 화면 위에 레이어를 씌우듯 두더지를 돌아다니게 해야하는데, 두더지가 돌아다니는 특정 웹페이지 개발은 가능합니다. 하지만 원하는건 그게 아닌듯 한데요. 

웬만하면 오케이하고싶지만, 개발적으로 이슈가 되는 부분은 크게 두가지입니다..
*  사용자가 어떤 페이지를 보고 있던지 컴퓨터 화면에 두더지 캐릭터가 돌아다니게 한다 
  - 말씀드렸듯 프로그램 개발에 가까운 스펙이라 웹 개발로 풀어낼 수가 없습니다. 
  - 웹쪽으로 풀어본다고 하면, 사용자가 현재 보고있는 페이지에 두더지 이미지를 주입시켜야하는데 그렇게 할 경우
     - 해당 웹 페이지의 구조를 건들기 때문에 웹페이지의 UI가 어긋날 수 있습니다. (가운데 있던 텍스트 박스가 갑자기 오른쪽으로 붙는다거나...)
     - 웹 보안정책상 코드 인젝션(code injection)은 제한이 많습니다. 악용의 소지가 많아서요. 유해한 코드를 집어넣을수도 있으니까요.. 
     - 크롬 익스텐션을 이용하면 이걸 조금 우회할수있긴 한데, 앞서 말했던 기존 페이지 UI 정합성 문제는 여전히 존재합니다...
*  커뮤니티 형성의 어려움 
  - `두더집사들이 모여서 서로의 즐거웠던 경험을 공유해 새로운 커뮤니티를 구성할 수 있게 도와준다`
  - 여러 사용자가 이야기를 나눌 수 있는 **커뮤니티를 만든다는 것 자체가 굉장히 큰 스펙**이고, 서버도 따로 운영해야하기 때문에 실질적인 금전적 비용이 발생할 겁니다. 
  - 토이프로젝트로 시도하기엔 비현실적입니다.. 미안합니다.. 


형배가 처음에 말한 두더지게임은 내가 '안 만들어요' 라고 의사전달을 한 것 같은데 이제 보니 너무 두루뭉술하게 대답한 감이 있네... 
<img width="356" alt="2019-03-01 1 40 52" src="https://user-images.githubusercontent.com/22616716/53582610-2b24bc00-3bc3-11e9-9aa0-0ae323fb59e5.png">
나는 민재의 수달처럼, 두더지도 '나만의 두더지를 찾아보자' 인 줄 알았어. 두더지도 되냐길래 랜덤 or 질문지 선택으로 다양한 두더지 보여주는 방식으로 선회한줄 이해함 ㅠ 

커뮤니케이션 미스였네요 ㅠ 미안합니다 🙇‍♀️ 
민재의 수달 컨텐츠처럼 진행할 것이 아니라면, 여기에 적어주신 기획안은 나중에 역량이 되는 개발자를 만나면 빛을 발하길 바랍니다....ㅠㅠ 

쓸까말까 고민하다가 괜히 네 시간 뺏기 싫어서(기껏 고민해놨는데 개발자가 못한다고 하면...) 조심스럽지만 솔직하게 글 남겨봅니당

**Comment by brothership** [comment]
@YeThor 나아갈 방향 알려주셔서 감사합니다. 이 프로젝트는 차차 제가 준비해보는것으로 하고 수달에 역량 집중해보는게 좋을 것 같군요

**Comment by YeThor** [comment]
여담이지만, 보통 현업에서는 이런 경우 때문에 초기 스펙 디자인 & 기획 회의부터 개발자 / 기획자 / 디자이너 / 프로덕트 매니저(PM)이 다함께 모여 얘기를 나누곤 합니다. 이건 내가 확실히 물어봤어야했당 ㅠㅠ ㅈㅅㅈㅅ

**Comment by YeThor** [comment]
헐 이시간에 코멘트가 달리다니 열심히 수정하고있었는데..

**Comment by YeThor** [comment]
프로젝트 완료로 해당 이슈 닫아둡니당
