### ISSUE TITLE
프로젝트 참여 가이드 

### ISSUE THREAD

**Issue by YeThor** [YeThor/What-is-your-otter#5]
프로젝트에 참여하고 싶은 분들을 위한 가이드입니다 

## ToC
- 이건 무슨 프로젝트죠?
- 저는 어떤 부분을 참여하게 되나요? 
- 어떻게 참여하면 되죠?
- 일정이 있나요? 

## 이건 무슨 프로젝트죠?
- 질문에 대한 선택지에 따라, 혹은 랜덤하게 사용자에게 컨텐츠를 보여주는 간단한 토이프로젝트 사이트입니다.
  - https://www.arealme.com/spirit-animal-quiz/ko/ 와 같은 부류라고 생각하시면 됩니다.
  - 단순 재미용 사이트입니다 
- 컨텐츠 형태만 다를뿐 기본적인 흐름은 똑같습니다. 
  - 유저가 선택하고,
  - 결과물을 받습니다.
  -  이 결과물은 다양한 타입의 수달이 될수도, 두더지가 될수도, 붕어빵이 될수도, 콜라가 될수도 있습니다.

## 저는 어떤 부분을 참여하게 되나요? 
- 프로젝트에 참여하시게 되는 부분은 앞서 서술한 **컨텐츠** 작업입니다. 
- 여러분의 상상력을 마음껏 펼쳐주세요
- 아래와 같은 작업이 필요합니다
  - 어떤 방식으로 (선택지, 랜덤형) 
  - 어떤 그림과 (.png, 여력이 된다면 .svg 파일)
  - 어떤 설명문 (문구)을 서빙할 것인지 
- 예시를 들자면 
  - 5개의 질문지와 
  - 두턱 수달의 그림과
  - 두턱 수달에 대한 설명문

## 어떻게 참여하면 되죠?
- 저에게 github ID를 말씀해주시고, 초대링크를 받아주세요. 그래야 collaborator로 등록되어 협업이 가능해집니다
- [Issue 보드를](https://github.com/YeThor/What-is-your-otter/issues) 자유롭게 사용해주세요. 마음껏 본문과 덧글을 작성하면 됩니당 
- 깃헙에서는 마크다운 언어 작성도 가능합니다. 쉬워요. 이 기회에 한번 해봐요
  - https://gist.github.com/ihoneymon/652be052a0727ad59601
  - 예시) `# 제목1` 이라고 타이핑하고 preview로 확인해보면, 크고 굵직하게 작성된 제목1을 볼 수 있습니다 
- `나만의 아이디어를 펼치고 싶어요`
  - 자신만의 아이디어를 담은 이슈글을 파서 진행합니다
  - 예시) [수달 기획&디자인](https://github.com/YeThor/What-is-your-otter/issues/2)
- `남의 아이디어를 확장시키고 싶어요`
  - 해당 아이디어 이슈글에 덧글로 자유로이 참여해주세요  

## 일정이 있나요? 
- 결론부터 말하자면, **없습니다** 
- 개발과 기획은 별도 트랙으로 진행할 예정입니다. 개발의 경우 4월말 최종 완료를 목표로 하고 있습니다.
- 하나의 컨텐츠가 완성되면, 바로 해당 내용을 반영할 것입니다
  - 예시) 15종의 수달그림과 설명문, 그리고 선택지 등의 작업이 완료되었을 경우 

## 전 개발에도 관심이 있는데요 
- 코드를 좀 보고싶다..하시는 분이 계시면 편하게 덧글달아주세요. 한분이라도 계시면 PR로 작업을 진행하며, 리뷰어로 지정해드리겠습니다.
- 원하는 분이 있으면 나중에 오프라인이나 트위치로 정말 간단하게 웹 사이트 강의를 할 수도 있겠네요.

**Comment by YeThor** [comment]
Readme.md로 반영

**Comment by brothership** [comment]
> 프로젝트에 참여하고 싶은 분들을 위한 가이드입니다
> 
> ## ToC
> * 이건 무슨 프로젝트죠?
> * 저는 어떤 부분을 참여하게 되나요?
> * 어떻게 참여하면 되죠?
> * 일정이 있나요?
> 
> ## 이건 무슨 프로젝트죠?
> * 질문에 대한 선택지에 따라, 혹은 랜덤하게 사용자에게 컨텐츠를 보여주는 간단한 토이프로젝트 사이트입니다.
>   
>   * https://www.arealme.com/spirit-animal-quiz/ko/ 와 같은 부류라고 생각하시면 됩니다.
>   * 단순 재미용 사이트입니다
> * 컨텐츠 형태만 다를뿐 기본적인 흐름은 똑같습니다.
>   
>   * 유저가 선택하고,
>   * 결과물을 받습니다.
>   * 이 결과물은 다양한 타입의 수달이 될수도, 두더지가 될수도, 붕어빵이 될수도, 콜라가 될수도 있습니다.
> 
> ## 저는 어떤 부분을 참여하게 되나요?
> * 프로젝트에 참여하시게 되는 부분은 앞서 서술한 **컨텐츠** 작업입니다.
> * 여러분의 상상력을 마음껏 펼쳐주세요
> * 아래와 같은 작업이 필요합니다
>   
>   * 어떤 방식으로 (선택지, 랜덤형)
>   * 어떤 그림과 (.png, 여력이 된다면 .svg 파일)
>   * 어떤 설명문 (문구)을 서빙할 것인지
> * 예시를 들자면
>   
>   * 5개의 질문지와
>   * 두턱 수달의 그림과
>   * 두턱 수달에 대한 설명문
> 
> ## 어떻게 참여하면 되죠?
> * 저에게 github ID를 말씀해주시고, 초대링크를 받아주세요. 그래야 collaborator로 등록되어 협업이 가능해집니다
> * [Issue 보드를](https://github.com/YeThor/What-is-your-otter/issues) 자유롭게 사용해주세요. 마음껏 본문과 덧글을 작성하면 됩니당
> * 깃헙에서는 마크다운 언어 작성도 가능합니다. 쉬워요. 이 기회에 한번 해봐요
>   
>   * https://gist.github.com/ihoneymon/652be052a0727ad59601
>   * 예시) `# 제목1` 이라고 타이핑하고 preview로 확인해보면, 크고 굵직하게 작성된 제목1을 볼 수 있습니다
> * `나만의 아이디어를 펼치고 싶어요`
>   
>   * 자신만의 아이디어를 담은 이슈글을 파서 진행합니다
>   * 예시) [수달 기획&디자인](https://github.com/YeThor/What-is-your-otter/issues/2)
> * `남의 아이디어를 확장시키고 싶어요`
>   
>   * 해당 아이디어 이슈글에 덧글로 자유로이 참여해주세요
> 
> ## 일정이 있나요?
> * 결론부터 말하자면, **없습니다**
> * 개발과 기획은 별도 트랙으로 진행할 예정입니다. 개발의 경우 4월말 최종 완료를 목표로 하고 있습니다.
> * 하나의 컨텐츠가 완성되면, 바로 해당 내용을 반영할 것입니다
>   
>   * 예시) 15종의 수달그림과 설명문, 그리고 선택지 등의 작업이 완료되었을 경우
> 
> ## 전 개발에도 관심이 있는데요
> * 코드를 좀 보고싶다..하시는 분이 계시면 편하게 덧글달아주세요. 한분이라도 계시면 PR로 작업을 진행하며, 리뷰어로 지정해드리겠습니다.
> * 원하는 분이 있으면 나중에 오프라인이나 트위치로 정말 간단하게 웹 사이트 강의를 할 수도 있겠네요.

**Comment by brothership** [comment]
@YeThor 개발에 관심 있습니다! 코드 보고 싶기는 한데.. 혹시 번거로운 과정이 필요한거면 그냥 패스해주시면 감사하겠습니다.

**Comment by YeThor** [comment]
@brothership ㅇㅋㅇㅋ
