### ISSUE TITLE
CI 시스템 도입에 대한 고민 

### ISSUE THREAD

**Issue by YeThor** [YeThor/what-is-your-otter#7]
### Why? 
사내에서 쓰는 것은 Jenkins이지만, 이걸 사이드 프로젝트에선 쓸 수 없으니 사이드 프로젝트용으로 도입할만 CI 시스템을 고민해야한다 

### 무엇을 도입하나 
github에서 공식으로 추천해주는 것들은 다음과 같음 (https://github.com/marketplace/category/continuous-integration) 
- Travis는 많이 들어봤는데,,,
- CircleCI 사용자수가 제일 많네... 
- Jenkins 무료사용 가능한가?
- 위의 걸 검토해보자

**Comment by brothership** [comment]
CI 시스템이라는 것은 뭘까

**Comment by YeThor** [comment]
@brothership CI(Continous Integration, 지속적인 통합) 시스템은 마치 최종 수문장같은 역할로, 개발자가 작업한 코드를 돌려보고 문제가 없는지(에러검출) 확인하는 과정을 자동화하는거라 생각하면 편합니다. 

자세한건 https://12bme.tistory.com/151 의 첫번째 문단을 읽어보면 좋을것같음!

**Comment by ny0011** [comment]
Jenkins 무료 사용 가능요 
웹쪽에서 사용하는 CI는 어떤 용도로 쓰는거?
CI 구성했을 때 편리함이 환경 구성할 때 들어가는 공수보다 크면 ㄲㄲ

**Comment by YeThor** [comment]
사실 대규모 프로젝트도 아니고 프로덕션 레벨도 아니라서 필요없긴 한데.. 그냥 공부 겸 ㅋㅋ

**Comment by ny0011** [comment]
아하 조와용👍👍

**Comment by YeThor** [comment]
젠킨스로 가즈아! 🚀
